# Generated by Django 5.2.1 on 2025-11-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_tag",
                    models.CharField(
                        blank=True,
                        help_text="برچسب یا شناسه\u200cای برای مدل مرتبط با این رویداد.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "در انتظار ارسال"),
                            (2, "ارسال شده"),
                            (3, "ناموفق"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "log"), (2, "cache")], db_index=True, default=1
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="حداکثر تعداد دفعات تلاش مجدد برای ارسال رویداد.",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="تعداد دفعاتی که تاکنون برای ارسال رویداد تلاش شده است.",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="تاریخ و زمان ایجاد رکورد رویداد."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="تاریخ و زمان آخرین تغییرات روی رکورد رویداد.",
                    ),
                ),
                (
                    "delivered_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="تاریخ و زمان تحویل موفق رویداد به مقصد.",
                        null=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="داده\u200cهای اصلی رویداد به صورت JSON ذخیره می\u200cشود."
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="پیام خطا در صورت شکست در ارسال یا پردازش رویداد.",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="آدرس سرویس مبدا که این رویداد را تولید کرده است، برای callback یا ردیابی توسط مصرف\u200cکنندگان استفاده می\u200cشود.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "db_table": "outbox_outbox",
            },
        ),
    ]
